master:
  extraPorts:
  - name: ssh
    port: 2222
    externalPort: 22
    protocol: TCP
  - name: slvlistener-jen
    port: 50000
    externalPort: 50000
    protocol: TCP

agent:
  enabled: true
  image: fabiuse/jenkins-with-docker
  tag: latest
  alwaysPullImage: true
  privileged: true
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

networkPolicy:
  enabled: true